CREATE TABLE students (
    StudentId INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FirstName VARCHAR(80) NOT NULL,
    LastName VARCHAR(80) NOT NULL,
    Birthday DATE NOT NULL,
    City VARCHAR(50) NOT NULL
);